# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2.9-apache-node-browsers
      - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    environment:
      - APP_DEBUG: false
      - APP_ENV: testing
      - APP_KEY:
      - DB_CONNECTION: mysql
      - DATABASE: circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout

      - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      # prepare the database
      - run: php artisan migrate --env=testing --database=circle_test --force

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit
